export const MODULE = 'SUPER-ADMIN-DASHBOARD';

export const GET_MEMBERS = `${MODULE}/GET_MEMBERS`
export const GOT_MEMBERS = `${MODULE}/GOT_MEMBERS`

export const GET_ORGANIZATION_TYPE = `${MODULE}/GET_ORGANIZATION_TYPE`
export const GOT_ORGANIZATION_TYPE = `${MODULE}/GOT_ORGANIZATION_TYPE`

export const GET_TOTAL_ORGANIZATION = `${MODULE}/GET_TOTAL_ORGANIZATION`
export const GOT_TOTAL_ORGANIZATION = `${MODULE}/GOT_TOTAL_ORGANIZATION`


