export const MODULE = 'SUPER-ADMIN-ORGANIZATION';

export const GET_LIST = `${MODULE}/GET_LIST`
export const GOT_LIST = `${MODULE}/GOT_LIST`

export const GET_DETAIL = `${MODULE}/GET_DETAIL`
export const GOT_DETAIL = `${MODULE}/GOT_DETAIL`

export const GET_REGIONS = `${MODULE}/GET_REGIONS`
export const GOT_REGIONS = `${MODULE}/GOT_REGIONS`

export const GET_PROVINCES = `${MODULE}/GET_PROVINCES`
export const GOT_PROVINCES = `${MODULE}/GOT_PROVINCES`

export const GET_MUNICIPALITIES = `${MODULE}/GET_MUNICIPALITIES`
export const GOT_MUNICIPALITIES = `${MODULE}/GOT_MUNICIPALITIES`

export const GET_BARANGAYS = `${MODULE}/GET_BARANGAYS`
export const GOT_BARANGAYS = `${MODULE}/GOT_BARANGAYS`

export const CREATE = `${MODULE}/CREATE`
export const REMOVE = `${MODULE}/REMOVE`
export const UPDATE = `${MODULE}/UPDATE`

export const SET_FORM_DATA = `${MODULE}/SET_FORM_DATA`
export const CLEAR_FORM_DATA = `${MODULE}/CLEAR_FORM_DATA`


