export const MODULE = 'ADMIN-ORGANIZATION-DASHBOARD';

export const GET_ACTIVE_BRANCHES = `${MODULE}/GET_ACTIVE_BRANCHES`
export const GOT_ACTIVE_BRANCHES = `${MODULE}/GOT_ACTIVE_BRANCHES`

export const GET_MEMBERS_PER_BRANCH = `${MODULE}/GET_MEMBERS_PER_BRANCH`
export const GOT_MEMBERS_PER_BRANCH = `${MODULE}/GOT_MEMBERS_PER_BRANCH`

export const GET_TOTAL_BRANCH = `${MODULE}/GET_TOTAL_BRANCH`
export const GOT_TOTAL_BRANCH = `${MODULE}/GOT_TOTAL_BRANCH`
