export const MODULE = 'BRANCHES-ADMIN-ORGANIZATION';

export const GET_LIST = `${MODULE}/GET_LIST-A`
export const GOT_LIST = `${MODULE}/GOT_LIST-A`

export const GET_DETAILS = `${MODULE}/GET_DETAILS-A`
export const GOT_DETAILS = `${MODULE}/GOT_DETAILS-A`

export const GET_REGIONS = `${MODULE}/GET_REGIONS-A`
export const GOT_REGIONS = `${MODULE}/GOT_REGIONS-A`

export const GET_PROVINCES = `${MODULE}/GET_PROVINCES-A`
export const GOT_PROVINCES = `${MODULE}/GOT_PROVINCES-A`

export const GET_MUNICIPALITIES = `${MODULE}/GET_MUNICIPALITIES-A`
export const GOT_MUNICIPALITIES = `${MODULE}/GOT_MUNICIPALITIES-A`

export const GET_BARANGAYS = `${MODULE}/GET_BARANGAYS-A`
export const GOT_BARANGAYS = `${MODULE}/GOT_BARANGAYS-A`

export const GET_MEMBERS = `${MODULE}/GET_MEMBERS-A`
export const GOT_MEMBERS = `${MODULE}/GOT_MEMBERS-A`

export const CREATE_MEMBER = `${MODULE}/CREATE_MEMBER-A`
export const UPDATE_MEMBER = `${MODULE}/UPDATE_MEMBER-A`
export const REMOVE_MEMBER = `${MODULE}/REMOVE_MEMBER-A`

export const CREATE = `${MODULE}/CREATE-A`
export const REMOVE = `${MODULE}/REMOVE-A`
export const UPDATE = `${MODULE}/UPDATE-A`

export const SET_FORM_DATA = `${MODULE}/SET_FORM_DATA-A`
export const CLEAR_FORM_DATA = `${MODULE}/CLEAR_FORM_DATA-A`


