export const MODULE = 'AUTH';

export const AUTHENTICATE = 'AUTHENTICATE';
export const CHECK_AUTH = 'CHECK_AUTH';
export const LOGIN = 'LOGIN';
export const SIGN_OUT = 'SIGN_OUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT';
export const VERIFY_RESET_CODE = 'VERIFY_RESET_CODE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const REGISTER = 'REGISTER';
export const PROFILE = 'PROFILE';
export const RESET_AUTH = 'RESET_AUTH';
export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const PERMISSIONS = 'PERMISSIONS';

export const GET_REGIONS = `${MODULE}/GET_REGIONS-A`
export const GOT_REGIONS = `${MODULE}/GOT_REGIONS-A`

export const GET_PROVINCES = `${MODULE}/GET_PROVINCES-A`
export const GOT_PROVINCES = `${MODULE}/GOT_PROVINCES-A`

export const GET_MUNICIPALITIES = `${MODULE}/GET_MUNICIPALITIES-A`
export const GOT_MUNICIPALITIES = `${MODULE}/GOT_MUNICIPALITIES-A`

export const GET_BARANGAYS = `${MODULE}/GET_BARANGAYS-A`
export const GOT_BARANGAYS = `${MODULE}/GOT_BARANGAYS-A`

export const GET_MEMBERS = `${MODULE}/GET_MEMBERS-A`
export const GOT_MEMBERS = `${MODULE}/GOT_MEMBERS-A`

export const SET_FORM_DATA = `${MODULE}/SET_FORM_DATA-A`
export const CLEAR_FORM_DATA = `${MODULE}/CLEAR_FORM_DATA-A`


